version: "3.7" 
services: 
  db: 
    image: mysql:5.7 
    restart: always
    command:
    - --lower_case_table_names=1
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    container_name: mysql-test 
    ports:
      - "52312:3306" 
    environment: 
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=1234  
      - TZ=Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql